#index:
#    path: /
#    controller: App\Controller\DefaultController::index
offre_pdf:
    path: /offre/{id}/pdf
    controller: 'App\Controller\OffreController::generatePDF'
    methods: ['GET']
afficher_pourcentages_offres:
    path: /afficher-pourcentages-offres
    controller: 'App\Controller\PanierController::afficherPourcentagesOffres'
app_offre_weather:
    path: '/offre/weather/{city}'
    controller: 'App\Controller\OffreController::weather'
supprimer_offre_panier:
    path: '/supprimer-offre/{nomOffre}'
    controller: 'App\Controller\PanierController::supprimerOffrePanier'
search:
    path: /search
    controller: App\Controller\OffreController::search
live_search:
    path: '/live-search'
    controller: 'App\Controller\EvenementController::liveSearch'    
app_reservation_show:
    path: '/reservation/{idBillet}'
    controller: 'App\Controller\ReservationController::show'
    methods: ['GET']
app_reservation_add:
    path: '/reservation/add/{idevt}'
    controller: 'App\Controller\ReservationController::add'
generate_qr_page:
    path: '/generate_qr_page/{idevt}/{idBillet}'
    controller: 'App\Controller\ReservationController::generateQRPage'
event_like:
    path: '/{idevt}/{id}/like'
    controller: 'App\Controller\EvenementController::like'
    methods: ['GET']
event_dislike:
    path: '/{idevt}/{id}/dislike'
    controller: 'App\Controller\EvenementController::dislike'
    methods: ['GET']
app_reservationn_cancel:
    path: '/{id}/{idevt}/del'
    controller: 'App\Controller\ReservationController::annulerReservation'
    methods: ['POST']


